### ISSUE TITLE
First `npm start` exits after max call stack size exceeded 

### ISSUE THREAD

**Issue by overra** [martindale/melody#4]
```
$ npm start

> melody@0.1.0 start /Users/asnodgrass/play/melody
> node melody.js

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
[WARNING] Resource "Person" attribute `roles` has no type. You should consider adding one.
express-session deprecated undefined resave option; provide resave option node_modules/maki-passport-local/index.js:67:25
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option node_modules/maki-passport-local/index.js:67:25
[SERVICE] [HTTP] listening for [http]       on  http://:::3000
[SERVICE] [HTTP] listening for [https,spdy] on https://:::3363
{ [MongoError: no collection]
  name: 'MongoError',
  message: 'no collection',
  ok: 0,
  errmsg: 'no collection',
  code: 26 }
/Users/asnodgrass/play/melody/node_modules/maki-mongoose-hooks/node_modules/fast-json-patch/src/json-patch-duplex.js:423
                if (obj.hasOwnProperty(key)) {
                        ^

RangeError: Maximum call stack size exceeded
    at Object.hasOwnProperty (native)
    at _unobserve (/Users/asnodgrass/play/melody/node_modules/maki-mongoose-hooks/node_modules/fast-json-patch/src/json-patch-duplex.js:423:25)
    at _unobserve (/Users/asnodgrass/play/melody/node_modules/maki-mongoose-hooks/node_modules/fast-json-patch/src/json-patch-duplex.js:426:25)
    at _unobserve (/Users/asnodgrass/play/melody/node_modules/maki-mongoose-hooks/node_modules/fast-json-patch/src/json-patch-duplex.js:426:25)
    at _unobserve (/Users/asnodgrass/play/melody/node_modules/maki-mongoose-hooks/node_modules/fast-json-patch/src/json-patch-duplex.js:426:25)
    at _unobserve (/Users/asnodgrass/play/melody/node_modules/maki-mongoose-hooks/node_modules/fast-json-patch/src/json-patch-duplex.js:426:25)
    at _unobserve (/Users/asnodgrass/play/melody/node_modules/maki-mongoose-hooks/node_modules/fast-json-patch/src/json-patch-duplex.js:426:25)
    at _unobserve (/Users/asnodgrass/play/melody/node_modules/maki-mongoose-hooks/node_modules/fast-json-patch/src/json-patch-duplex.js:426:25)
    at _unobserve (/Users/asnodgrass/play/melody/node_modules/maki-mongoose-hooks/node_modules/fast-json-patch/src/json-patch-duplex.js:426:25)
    at _unobserve (/Users/asnodgrass/play/melody/node_modules/maki-mongoose-hooks/node_modules/fast-json-patch/src/json-patch-duplex.js:426:25)

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/asnodgrass/.nvm/versions/node/v4.1.0/bin/node" "/Users/asnodgrass/.nvm/versions/node/v4.1.0/bin/npm" "start"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE
npm ERR! melody@0.1.0 start: `node melody.js`
npm ERR! Exit status 1
```

**Comment by overra** [comment]
Tried it again and now it's running but it seems like resources aren't being served.

**Comment by martindale** [comment]
I think this will unfortunately require node 0.12, as I have similar errors when trying with 4.x.  Looks like it's primarily due to `maki-mongoose-hooks`?
